title: Pour Over Concepts
email: pouroverconcepts@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Every great idea begins with coffee

url: ""
# Only necessary when hosting your site in a sub-directory. Project sites hosted on GitHub Pages are the common use-case of this variable.
baseurl: # Ex: /project-page
paginate_path: "blog/page:num/"
permalink: blog/:title/

#Header Option
#header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 6

navigation:
    - title: Home
      url: /index.html
    - title: About
      url: /about
    # - title: Contact
    #   url: /contact

# social:
#     github: brianmaierjr
#     twitter: brianmaierjr
#     facebook: brianmaierjr
#     email: brimaidesigns@gmail.com
#     linkedin: brianmaierjr
#     youtube: RickAstleyYT
#     tumblr: i-am-a-fish

#google_analytics: "UA-58263416-1"

#